### ISSUE TITLE
Переделать параметры и возвращаемый результат в int

### ISSUE THREAD

**Issue by coursar** [aybatova/CreditServise#4]
Конвертируйте внутри в double, если нужно:
https://github.com/aybatova/CreditServise/blob/b8a2d2a181d16a6339817609ec3d84e9391019b7/src/main/java/ru/itpark/CreditService.java#L6

Math.round возвращает int/long, поэтому в качестве результата также возвращайте int/long:
https://github.com/aybatova/CreditServise/blob/b8a2d2a181d16a6339817609ec3d84e9391019b7/src/main/java/ru/itpark/CreditService.java#L16

**Comment by aybatova** [comment]
return (double) Math.round(pay);

так?

**Comment by coursar** [comment]
@aybatova, нет, вот так:
```java
public int calcualteCredit(...) {
    ...
    return Math.round(pay);
}
```

**Comment by aybatova** [comment]
public int calculateCredit(double creditSum, double creditPeriod, double creditRate)
...

            return (int) Math.round(pay);

**Comment by coursar** [comment]
@aybatova, если int - то да, если long - то не нужно.
